export const worldCurrencies = [
  { value: 'AED', label: 'United Arab Emirates dirham', symbol: '' },
  { value: 'AFN', label: 'Afghan afghani', symbol: '' },
  { value: 'ALL', label: 'Albanian lek', symbol: '' },
  { value: 'AMD', label: 'Armenian dram', symbol: '' },
  { value: 'ANG', label: 'Netherlands Antillean guilder', symbol: '' },
  { value: 'AOA', label: 'Angolan kwanza', symbol: '' },
  { value: 'ARS', label: 'Argentine peso', symbol: '' },
  { value: 'AUD', label: 'Australian dollar', symbol: '' },
  { value: 'AWG', label: 'Aruban florin', symbol: '' },
  { value: 'AZN', label: 'Azerbaijani manat', symbol: '' },
  {
    value: 'BAM',
    label: 'Bosnia and Herzegovina convertible mark',
    symbol: ''
  },
  { value: 'BBD', label: 'Barbados dollar', symbol: '' },
  { value: 'BDT', label: 'Bangladeshi taka', symbol: '' },
  { value: 'BGN', label: 'Bulgarian lev', symbol: '' },
  { value: 'BHD', label: 'Bahraini dinar', symbol: '' },
  { value: 'BIF', label: 'Burundian franc', symbol: '' },
  { value: 'BMD', label: 'Bermudian dollar', symbol: '' },
  { value: 'BND', label: 'Brunei dollar', symbol: '' },
  { value: 'BOB', label: 'Boliviano', symbol: '' },
  { value: 'BRL', label: 'Brazilian real', symbol: '' },
  { value: 'BSD', label: 'Bahamian dollar', symbol: '' },
  { value: 'BTN', label: 'Bhutanese ngultrum', symbol: '' },
  { value: 'BWP', label: 'Botswana pula', symbol: '' },
  { value: 'BYN', label: 'New Belarusian ruble', symbol: '' },
  { value: 'BYR', label: 'Belarusian ruble', symbol: '' },
  { value: 'BZD', label: 'Belize dollar', symbol: '' },
  { value: 'CAD', label: 'Canadian dollar', symbol: '' },
  { value: 'CDF', label: 'Congolese franc', symbol: '' },
  { value: 'CHF', label: 'Swiss franc', symbol: '' },
  { value: 'CLF', label: 'Unidad de Fomento', symbol: '' },
  { value: 'CLP', label: 'Chilean peso', symbol: '' },
  { value: 'CNY', label: 'Renminbi|Chinese yuan', symbol: '' },
  { value: 'COP', label: 'Colombian peso', symbol: '' },
  { value: 'CRC', label: 'Costa Rican colon', symbol: '₡' },
  { value: 'CUC', label: 'Cuban convertible peso', symbol: '' },
  { value: 'CUP', label: 'Cuban peso', symbol: '' },
  { value: 'CVE', label: 'Cape Verde escudo', symbol: '' },
  { value: 'CZK', label: 'Czech koruna', symbol: '' },
  { value: 'DJF', label: 'Djiboutian franc', symbol: '' },
  { value: 'DKK', label: 'Danish krone', symbol: '' },
  { value: 'DOP', label: 'Dominican peso', symbol: '' },
  { value: 'DZD', label: 'Algerian dinar', symbol: '' },
  { value: 'EGP', label: 'Egyptian pound', symbol: '' },
  { value: 'ERN', label: 'Eritrean nakfa', symbol: '' },
  { value: 'ETB', label: 'Ethiopian birr', symbol: '' },
  { value: 'EUR', label: 'Euro', symbol: '€' },
  { value: 'FJD', label: 'Fiji dollar', symbol: '' },
  { value: 'FKP', label: 'Falkland Islands pound', symbol: '' },
  { value: 'GBP', label: 'Pound sterling', symbol: '£' },
  { value: 'GEL', label: 'Georgian lari', symbol: '' },
  { value: 'GHS', label: 'Ghanaian cedi', symbol: '' },
  { value: 'GIP', label: 'Gibraltar pound', symbol: '' },
  { value: 'GMD', label: 'Gambian dalasi', symbol: '' },
  { value: 'GNF', label: 'Guinean franc', symbol: '' },
  { value: 'GTQ', label: 'Guatemalan quetzal', symbol: '' },
  { value: 'GYD', label: 'Guyanese dollar', symbol: '' },
  { value: 'HKD', label: 'Hong Kong dollar', symbol: '' },
  { value: 'HNL', label: 'Honduran lempira', symbol: '' },
  { value: 'HRK', label: 'Croatian kuna', symbol: '' },
  { value: 'HTG', label: 'Haitian gourde', symbol: '' },
  { value: 'HUF', label: 'Hungarian forint', symbol: '' },
  { value: 'IDR', label: 'Indonesian rupiah', symbol: '' },
  { value: 'ILS', label: 'Israeli new shekel', symbol: '₪' },
  { value: 'INR', label: 'Indian rupee', symbol: '₹' },
  { value: 'IQD', label: 'Iraqi dinar', symbol: '' },
  { value: 'IRR', label: 'Iranian rial', symbol: '' },
  { value: 'ISK', label: 'Icelandic króna', symbol: '' },
  { value: 'JMD', label: 'Jamaican dollar', symbol: '' },
  { value: 'JOD', label: 'Jordanian dinar', symbol: '' },
  { value: 'JPY', label: 'Japanese yen', symbol: '¥' },
  { value: 'KES', label: 'Kenyan shilling', symbol: '' },
  { value: 'KGS', label: 'Kyrgyzstani som', symbol: '' },
  { value: 'KHR', label: 'Cambodian riel', symbol: '' },
  { value: 'KMF', label: 'Comoro franc', symbol: '' },
  { value: 'KPW', label: 'North Korean won', symbol: '' },
  { value: 'KRW', label: 'South Korean won', symbol: '₩' },
  { value: 'KWD', label: 'Kuwaiti dinar', symbol: '' },
  { value: 'KYD', label: 'Cayman Islands dollar', symbol: '' },
  { value: 'KZT', label: 'Kazakhstani tenge', symbol: '' },
  { value: 'LAK', label: 'Lao kip', symbol: '' },
  { value: 'LBP', label: 'Lebanese pound', symbol: '' },
  { value: 'LKR', label: 'Sri Lankan rupee', symbol: '' },
  { value: 'LRD', label: 'Liberian dollar', symbol: '' },
  { value: 'LSL', label: 'Lesotho loti', symbol: '' },
  { value: 'LYD', label: 'Libyan dinar', symbol: '' },
  { value: 'MAD', label: 'Moroccan dirham', symbol: '' },
  { value: 'MDL', label: 'Moldovan leu', symbol: '' },
  { value: 'MGA', label: 'Malagasy ariary', symbol: '' },
  { value: 'MKD', label: 'Macedonian denar', symbol: '' },
  { value: 'MMK', label: 'Myanmar kyat', symbol: '' },
  { value: 'MNT', label: 'Mongolian tögrög', symbol: '' },
  { value: 'MOP', label: 'Macanese pataca', symbol: '' },
  { value: 'MRO', label: 'Mauritanian ouguiya', symbol: '' },
  { value: 'MUR', label: 'Mauritian rupee', symbol: '' },
  { value: 'MVR', label: 'Maldivian rufiyaa', symbol: '' },
  { value: 'MWK', label: 'Malawian kwacha', symbol: '' },
  { value: 'MXN', label: 'Mexican peso', symbol: '' },
  { value: 'MXV', label: 'Mexican Unidad de Inversion', symbol: '' },
  { value: 'MYR', label: 'Malaysian ringgit', symbol: '' },
  { value: 'MZN', label: 'Mozambican metical', symbol: '' },
  { value: 'NAD', label: 'Namibian dollar', symbol: '' },
  { value: 'NGN', label: 'Nigerian naira', symbol: '₦' },
  { value: 'NIO', label: 'Nicaraguan córdoba', symbol: '' },
  { value: 'NOK', label: 'Norwegian krone', symbol: '' },
  { value: 'NPR', label: 'Nepalese rupee', symbol: '' },
  { value: 'NZD', label: 'New Zealand dollar', symbol: '' },
  { value: 'OMR', label: 'Omani rial', symbol: '' },
  { value: 'PAB', label: 'Panamanian balboa', symbol: '' },
  { value: 'PEN', label: 'Peruvian Sol', symbol: '' },
  { value: 'PGK', label: 'Papua New Guinean kina', symbol: '' },
  { value: 'PHP', label: 'Philippine peso', symbol: '₱' },
  { value: 'PKR', label: 'Pakistani rupee', symbol: '' },
  { value: 'PLN', label: 'Polish złoty', symbol: 'zł' },
  { value: 'PYG', label: 'Paraguayan guaraní', symbol: '₲' },
  { value: 'QAR', label: 'Qatari riyal', symbol: '' },
  { value: 'RON', label: 'Romanian leu', symbol: '' },
  { value: 'RSD', label: 'Serbian dinar', symbol: '' },
  { value: 'RUB', label: 'Russian ruble', symbol: '' },
  { value: 'RWF', label: 'Rwandan franc', symbol: '' },
  { value: 'SAR', label: 'Saudi riyal', symbol: '' },
  { value: 'SBD', label: 'Solomon Islands dollar', symbol: '' },
  { value: 'SCR', label: 'Seychelles rupee', symbol: '' },
  { value: 'SDG', label: 'Sudanese pound', symbol: '' },
  { value: 'SEK', label: 'Swedish krona', symbol: '' },
  { value: 'SGD', label: 'Singapore dollar', symbol: '' },
  { value: 'SHP', label: 'Saint Helena pound', symbol: '' },
  { value: 'SLL', label: 'Sierra Leonean leone', symbol: '' },
  { value: 'SOS', label: 'Somali shilling', symbol: '' },
  { value: 'SRD', label: 'Surilabelse dollar', symbol: '' },
  { value: 'SSP', label: 'South Sudanese pound', symbol: '' },
  { value: 'STD', label: 'São Tomé and Príncipe dobra', symbol: '' },
  { value: 'SVC', label: 'Salvadoran colón', symbol: '' },
  { value: 'SYP', label: 'Syrian pound', symbol: '' },
  { value: 'SZL', label: 'Swazi lilangeni', symbol: '' },
  { value: 'THB', label: 'Thai baht', symbol: '฿' },
  { value: 'TJS', label: 'Tajikistani somoni', symbol: '' },
  { value: 'TMT', label: 'Turkmenistani manat', symbol: '' },
  { value: 'TND', label: 'Tunisian dinar', symbol: '' },
  { value: 'TOP', label: 'Tongan paʻanga', symbol: '' },
  { value: 'TRY', label: 'Turkish lira', symbol: '' },
  { value: 'TTD', label: 'Trinidad and Tobago dollar', symbol: '' },
  { value: 'TWD', label: 'New Taiwan dollar', symbol: '' },
  { value: 'TZS', label: 'Tanzanian shilling', symbol: '' },
  { value: 'UAH', label: 'Ukrainian hryvnia', symbol: '₴' },
  { value: 'UGX', label: 'Ugandan shilling', symbol: '' },
  { value: 'USD', label: 'United States dollar', symbol: '$' },
  { value: 'UYI', label: 'Uruguay Peso en Unidades Indexadas', symbol: '' },
  { value: 'UYU', label: 'Uruguayan peso', symbol: '' },
  { value: 'UZS', label: 'Uzbekistan som', symbol: '' },
  { value: 'VEF', label: 'Venezuelan bolívar', symbol: '' },
  { value: 'VND', label: 'Vietlabelse đồng', symbol: '₫' },
  { value: 'VUV', label: 'Vanuatu vatu', symbol: '' },
  { value: 'WST', label: 'Samoan tala', symbol: '' },
  { value: 'XAF', label: 'Central African CFA franc', symbol: '' },
  { value: 'XCD', label: 'East Caribbean dollar', symbol: '' },
  { value: 'XOF', label: 'West African CFA franc', symbol: '' },
  { value: 'XPF', label: 'CFP franc', symbol: '' },
  { value: 'XXX', label: 'No currency', symbol: '' },
  { value: 'YER', label: 'Yemeni rial', symbol: '' },
  { value: 'ZAR', label: 'South African rand', symbol: '' },
  { value: 'ZMW', label: 'Zambian kwacha', symbol: '' },
  { value: 'ZWL', label: 'Zimbabwean dollar', symbol: '' }
];
